# LLM Configuration Defaults
model: "moonshotai/kimi-k2:free"
n_consistency: 3
temperature: 0.0
top_p: 1.0
max_tokens: 800
retries:
  stop_after_attempt: 5
  wait_exponential_multiplier: 0.5
  wait_exponential_min: 0.5
  wait_exponential_max: 4.0