name: bench-baseline

on:
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "proofengine/metrics.py"
      - "proofengine/orchestrator/modes.py"
      - ".github/workflows/bench-baseline.yml"

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - run: pip install -r requirements.txt
      
      - name: Run baseline benchmark
        env:
          METRICS_FAIRNESS: "1"
        run: |
          python scripts/bench_2cat.py \
            --suite corpus/bench_public/suite.json \
            --mode baseline \
            --runs 3 \
            --out artifacts/bench_public/metrics_baseline.json \
            --verifier mock \
            --fairness
      
      - name: Upload baseline metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics_baseline
          path: artifacts/bench_public/metrics_baseline.json
