name: bench-public
on:
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "corpus/bench_public/**"
      - ".github/workflows/bench-public.yml"
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: python scripts/bench_2cat.py --suite corpus/bench_public/suite.json --mode baseline --runs 1 --out artifacts/bench_public/metrics_baseline.json
      - run: python scripts/bench_2cat.py --suite corpus/bench_public/suite.json --mode active --runs 1 --out artifacts/bench_public/metrics_active.json
      - uses: actions/upload-artifact@v4
        with: { name: bench_public, path: artifacts/bench_public }
