name: bench-active

on:
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "proofengine/metrics.py"
      - "proofengine/orchestrator/modes.py"
      - ".github/workflows/bench-active.yml"

jobs:
  bench:
    runs-on: ubuntu-latest
    needs: []  # Add explicit dependency on bench-baseline job
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - run: pip install -r requirements.txt
      
      - name: Generate baseline metrics
        run: |
          python scripts/bench_2cat.py \
            --suite corpus/s2pp/suite.json \
            --modes baseline \
            --runs 3 \
            --out artifacts/bench_public/baseline/
      
      - name: Run active benchmark
        run: |
          python scripts/bench_2cat.py \
            --suite corpus/s2pp/suite.json \
            --modes active \
            --runs 3 \
            --out artifacts/bench_public/active/
      
      - name: Upload active metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics_active
          path: artifacts/bench_public/active/
