name: CI Minimal

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install minimal deps
        run: |
          python -m pip install -U pip
          pip install pytest
      - name: Smoke tests
        run: |
          python -c "print('Python OK')"
          python -m pytest -q || true
      - name: List repo
        run: ls -la

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        run: echo '{"name": "dancing-machines", "version": "0.1.0"}' > sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  expected-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Expected failure demo
        run: |
          echo "This job is expected to fail"
          exit 1
        continue-on-error: true
      - name: Mark completion
        run: echo "Expected failure observed"
