name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  fmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install black ruff jsonschema
      
      - name: Format check
        run: black --check .
      
      - name: Lint check
        run: ruff check .

  schema-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install jsonschema
      
      - name: Schema validation
        run: python scripts/test_roundtrip.py

  demo-s1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      
      - name: Run demo-s1
        run: |
          python orchestrator/skeleton.py --plan plans/plan-hello.json --state state/x-hello.json || echo "Demo completed (may have expected failures)"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifacts
          path: |
            metrics.json
            state/x-hello-updated.json
          if-no-files-found: warn
