name: Expected Fail Demo - DISABLED

# DISABLED: Using expected-fail-simple.yml instead
on:
  workflow_dispatch:

jobs:
  demo-s1-expected-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.lock
          
      - name: Create test case with secret injection
        run: |
          mkdir -p test_secret_case
          cat > test_secret_case/secret_test.py << 'EOF'
          def process_data(data):
              # This should trigger OPA policy violation
              api_key = "sk-1234567890abcdef"  # SECRET INJECTED
              return data + api_key
          EOF
          
      - name: Run demo with expected failure
        run: |
          # This should fail with policy_violation
          python orchestrator/skeleton.py \
            --plan plans/plan-hello.json \
            --state state/x-hello.json \
            --test-case test_secret_case || echo "Expected failure: policy_violation"
            
      - name: Verify OPA policy triggered
        run: |
          # Check that OPA detected the secret
          if grep -q "no-secrets" logs/opa.log 2>/dev/null; then
            echo "✅ OPA policy 'no-secrets' triggered as expected"
          else
            echo "❌ OPA policy not triggered - this is unexpected"
            exit 1
          fi
