name: Proof CI (Simple)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: proof-ci-simple-${{ github.ref }}
  cancel-in-progress: true

jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal dependencies
        run: |
          python -m pip install -U pip
          pip install --quiet pytest || true

      - name: Repository smoke check
        run: |
          echo "Listing repository root"
          ls -la
          echo "Proof CI simple smoke check complete"
